### PR TITLE
move server runner's enable_dualstack to ServerDeploymentArgs

### PR DESCRIPTION
**Pull request by purnesh42H**

### CODE REVIEW

**Comment by purnesh42H** [comment]
- [ ] [grpc/core/master/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/e053d626-1ba2-400e-aa9c-b6b31886ebdf)
- [ ] [grpc/core/master/linux/grpc_xds_url_map](https://source.cloud.google.com/results/invocations/3d440656-5fcf-41a9-bc56-768ad66db956)
- [ ] [grpc/core/master/linux/grpc_xds_v3](https://source.cloud.google.com/results/invocations/0654e08e-cf32-49a7-8d23-a1f357add888)
- [ ] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/e59a5722-867f-4b27-ab35-0482151c0fbc)

**Review by larry-safran — APPROVED** [review]
As long as the tests still work, it seems okay to me.

**Comment by purnesh42H** [comment]
> As long as the tests still work, it seems okay to me.

yeah i have put the test run above which succeeded

**Review by XuanWang-Amos — APPROVED** [review]
LGTM

**Comment by purnesh42H** [comment]
- [ ] [grpc/core/master/linux/psm-dualstack](https://source.cloud.google.com/results/invocations/ebbab986-b5d2-4888-946a-9f3f447ac56f)

**Pull request merged**
