### PR TITLE
[deps] Upgrade kubernetes python client from 27.2.0 to 30.1.0

### PR DESCRIPTION
**Pull request by purnesh42H**
Fixes: #102

### CODE REVIEW

**Review by sourabhsinghs — APPROVED** [review]

**Comment by XuanWang-Amos** [comment]
Have we tested this change yet? Please test this with both staging and prod tests and add links to description.

**Review by sergiitk — CHANGES_REQUESTED** [review]
Please update https://github.com/grpc/psm-interop/blob/main/requirements.txt as well

**Comment by purnesh42H** [comment]
> Please update https://github.com/grpc/psm-interop/blob/main/requirements.txt as well

Done

**Comment by XuanWang-Amos** [comment]
Adhoc kokoro run against cpp 1.65.x:
- [ ] [grpc/core/master/linux/grpc_xds_k8s_lb](https://source.cloud.google.com/results/invocations/dd4a407a-b5ae-4f06-880e-75be2cd1634a)
- [ ] [grpc/core/master/linux/grpc_xds_url_map](https://source.cloud.google.com/results/invocations/e0d40e68-1837-426d-a34b-0c7cfe6eb6cc)
- [ ] [grpc/core/master/linux/grpc_xds_v3](https://source.cloud.google.com/results/invocations/4e7c71f8-7cc1-4140-98d1-6d2d37cffcd8)
- [ ] [grpc/core/master/linux/psm-csm](https://source.cloud.google.com/results/invocations/a01511ee-c23f-4889-ab6a-0e28b92b2823)

**Comment by purnesh42H** [comment]
@XuanWang-Amos all runs have succeeded

**Review by XuanWang-Amos — APPROVED** [review]

**Review by sergiitk — APPROVED** [review]

**Pull request merged**
